# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup Java
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    # Setup Flutter SDK
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta'
    - name: Enable web support
      run: flutter config --enable-web

    # Runs a set of commands using the runners shell
    - name: Get packages
      run: flutter pub get
    # No test yet
    - name: Build
      run: flutter build web
    
    # Publish to Github Pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        
